job/urls.py
from django.urls import path, include
from . import views

app_name = "job"

urlpatterns = [
    path("jobs/get", views.get_jobs, name="get_jobs"),
    path("list", views.list, name="list"),
    path("detail/<int:id>", views.detail, name="detail"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("test/list", views.test_list, name="test_list"),
    path("test/detail/<int:id>", views.test_detail, name="test_detail"),
    path("test/finish/<int:id>", views.finish_test, name="finish_test"),
    path("test/next-machine/<int:id>", views.next_machine, name="next_machine"),
    # path("test/edit/<int:id>", views.test_edit, name="test_edit"),
    path("test/create/<int:id>", views.create_test, name="create_test"),
    path(
        "test/semi-waste/create/<int:id>",
        views.create_semi_waste,
        name="create_semi_waste",
    ),
]

main/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password/change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/profile/password/change.html"
        ),
        name="password_change",
    ),
    path(
        "password/change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/profile/password/done.html"
        ),
        name="password_change_done",
    ),
    path("", include("account.urls")),
    path("approval/", include("approval.urls")),
    path("product/", include("product.urls")),
    path("job/", include("job.urls")),
    path("misc/", include("misc.urls")),
    path("machine/", include("machine.urls")),
    path("assessment/", include("assessment.urls")),
    path("she/", include("she.urls")),
    path("report/", include("report.urls")),
    re_path(r"^session_security/", include("session_security.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she/urls.py
from django.urls import path
from . import views

app_name = "she"

urlpatterns = [
    # path("edit/<int:id>", views.edit, name="edit"),
    path("issue/list", views.issue_list, name="issue_list"),
    path("issue/create", views.create_issue, name="create_issue"),
    path("issue/detail/<int:id>", views.issue_detail, name="issue_detail"),
    path(
        "status/update/<int:id>/<str:action>", views.update_status, name="update_status"
    ),
    path("incident/list", views.incident_list, name="incident_list"),
    path("incident/create", views.create_incident, name="create_incident"),
    path("incident/detail/<int:id>", views.incident_detail, name="incident_detail"),
    path("department/list", views.department_list, name="department_list"),
    path("department/get", views.get_departments, name="get_departments"),
    path("employee/list", views.employee_list, name="employee_list"),
    path("employee/get", views.get_employees, name="get_employees"),
    path("location/list", views.location_list, name="location_list"),
    path("location/create", views.create_location, name="create_location"),
    path("location/edit/<int:id>", views.edit_location, name="edit_location"),
    path("issue/type/list", views.issue_type_list, name="issue_type_list"),
    path("issue/type/create", views.create_issue_type, name="create_issue_type"),
    path("issue/type/edit/<int:id>", views.edit_issue_type, name="edit_issue_type"),
    path("incident/type/list", views.incident_type_list, name="incident_type_list"),
    path(
        "incident/type/create", views.create_incident_type, name="create_incident_type"
    ),
    path(
        "incident/type/edit/<int:id>",
        views.edit_incident_type,
        name="edit_incident_type",
    ),
    path(
        "fire-prevention/list", views.fire_prevention_list, name="fire_prevention_list"
    ),
    path(
        "fire-prevention/create",
        views.create_fire_prevention,
        name="create_fire_prevention",
    ),
    path(
        "fire-prevention/detail/<int:id>",
        views.fire_prevention_detail,
        name="fire_prevention_detail",
    ),
    path(
        "fire-prevention/checklist/save/<int:id>",
        views.save_fp_checklist,
        name="save_fp_checklist",
    ),
    path(
        "fire-prevention/checkpoint/list", views.checkpoint_list, name="checkpoint_list"
    ),
    path(
        "fire-prevention/checkpoint/create",
        views.create_checkpoint,
        name="create_checkpoint",
    ),
    path(
        "fire-prevention/checkpoint/edit/<int:id>",
        views.edit_checkpoint,
        name="edit_checkpoint",
    ),
]

templates/issue/create.html
{% extends "form.html" %}
{% block title %}Create S.H.E. Issue{% endblock %}
{% block form %}
    <div class=" bg-gray-50 max-w-lg mx-auto">
        <form class="p-2 md:p-5 "
              enctype="multipart/form-data"
              method="post"
              action="{% url 'she:create_issue' %}">
            {% csrf_token %}
            <div class="flex-col gap-2 mb-4 mx-auto px-2">
                <p class="text-red-700 text-sm">
                    {% if form.non_field_errors %}{{ form.non_field_errors|join:", " }}{% endif %}
                </p>
                <div class="grid sm:grid-cols-2 gap-2 mb-4">
                    {% for field in form %}
                        <div class="flex-col {% if field.name == 'observation' or field.name == 'department' or field.name == 'suggestion' %}sm:col-span-2{% endif %} justify-between gap-2 mb-4 ">
                            <div class=" mb-2">{{ field.label_tag }}</div>
                            <div class="flex ">{{ field }}</div>
                            <p class="text-red-700 text-sm">
                                {% if field.errors %}{{ field.errors|join:", " }}{% endif %}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="flex gap-4">
                <button type="submit"
                        class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Create
                </button>
                <a href="{% url 'she:issue_list' %}"
                   class=" inline-flex items-center bg-gray-200 hover:bg-gray-300 focus:ring-2 focus:outline-none focus:ring-gray-400 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Cancel
                </a>
            </div>
        </form>
        {{ form.media }}
    </div>
{% endblock form %}

templates/issue/detail.html
{% extends "base.html" %}
{% block title %}Issue Detail{% endblock %}
{% block content %}
    <div class="mx-auto ">
        <div class="w-full space-y-4 p-2 bg-white border border-gray-200 rounded-lg shadow sm:p-4">
            <div class="flex gap-2">
                <a href="{% url 'she:issue_list' %}">
                    <svg class="w-8 h-8 text-gray-800 "
                         aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24"
                         fill="none"
                         viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12l4-4m-4 4 4 4" />
                    </svg>
                </a>
                <p class="text-base md:text-lg font-semibold uppercase text-gray-600 ">
                    {{ issue.issue_type.name }} - {{ issue.location.name }}
                </p>
            </div>
            <div class="flex place-content-end">
                <div class="flex flex-wrap gap-4  ">
                    {% if issue.status == 'CREATED' %}
                        {% if request.user == issue.created_by %}{% endif %}
                        {% if request.user != issue.created_by or request.user.profile.role == 'ADMIN' %}{% endif %}
                        <div>{% include 'issue/action/form.html' with id=issue.id action='CANCEL' %}</div>
                        <div>{% include 'issue/action/form.html' with id=issue.id action='CLOSE' %}</div>
                    {% elif issue.status == 'PENDING' %}
                        {% if request.user == issue.created_by %}{% endif %}
                        <div>{% include 'issue/action/form.html' with id=issue.id action='APPROVE' %}</div>
                        <div>{% include 'issue/action/form.html' with id=issue.id action='REJECT' %}</div>
                    {% endif %}
                    <div>{% include 'issue/remark/list.html' %}</div>
                </div>
            </div>
            <p class="text-base md:text-xl font-bold text-gray-600 ">{{ issue.job_test.job }}</p>
            <ul class="my-4 space-y-3">
                {% with status=issue.status %}
                    <li class=" rounded-lg">
                        <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 bg-gray-50 hover:bg-gray-100 group hover:shadow">
                            <div class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Status</div>
                            <div class="inline-flex items-center justify-center px-4 py-1.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 {% if status == 'CREATED' %} bg-CREATED {% elif status == 'CANCELLED' %} bg-CANCELLED {% elif status == 'ACCEPTED' %} bg-ACCEPTED {% elif status == 'REJECTED' %} bg-REJECTED {% elif status == 'IN-PROGRESS' %} bg-IN-PROGRESS {% elif status == 'PENDING' %} bg-PENDING {% elif status == 'INCOMPLETE' %} bg-INCOMPLETE {% elif status == 'COMPLETED' %} bg-COMPLETED {% endif %}text-white rounded">
                                {{ issue.status }}
                            </div>
                        </a>
                        <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 bg-gray-50 hover:bg-gray-100 group hover:shadow">
                            <div class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Remark</div>
                            <div class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-100 rounded">
                                {{ issue.remarks.first.text }}
                            </div>
                        </a>
                    </li>
                {% endwith %}
                {% if issue.status == 'COMPLETED' %}
                    <li>
                        <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow">
                            <span class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Completed @</span>
                            <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-200 rounded">{{ issue.remarks.first.created_at }}</span>
                        </a>
                    </li>
                {% endif %}
                <li>
                    <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow">
                        <span class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Location</span>
                        <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-200 rounded">{{ issue.location.name }}</span>
                    </a>
                </li>
                <li>
                    <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow">
                        <span class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Assigned To</span>
                        <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-200 rounded">{{ issue.department.name }}</span>
                    </a>
                </li>
                <li>
                    <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow">
                        <span class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Issue Type</span>
                        <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-200 rounded">{{ issue.issue_type.name }}</span>
                    </a>
                </li>
                <li>
                    <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow">
                        <span class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Created By</span>
                        <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-200 rounded">{{ issue.created_by.username }}</span>
                    </a>
                    <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow">
                        <span class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Created At</span>
                        <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-200 rounded">{{ issue.created_at }}</span>
                    </a>
                </li>
                <li>
                    <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow">
                        <span class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Observation</span>
                        <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-200 rounded">{{ issue.observation }}</span>
                    </a>
                </li>
                <li>
                    <a class="grid sm:grid-cols-2 items-center p-1 sm:p-3 text-sm md:text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow">
                        <span class="flex-1 mb-2 sm:mb-0 ms-3 whitespace-nowrap">Suggestion</span>
                        <span class="inline-flex items-center justify-center px-2 py-0.5 ms-3 text-xs md:text-sm font-semibold text-gray-700 bg-gray-200 rounded">{{ issue.suggestion }}</span>
                    </a>
                </li>
            </ul>
            {% if issue.image %}
                <div class="mt-4 w-fit  items-center mx-auto">
                    <img src="{{ issue.image.url }}"
                         alt="Artwork"
                         height=""
                         width=""
                         class=" h-auto w-full  rounded-lg" />
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/issue/list.html
{% extends "partials/table.html" %}
{% block title %}S.H.E. Issue List{% endblock %}
{% block buttons %}
    <a href="{% url 'she:create_issue' %}"
       class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
        Create
    </a>
    {% include "partials/filter.html" %}
{% endblock buttons %}
{% block table %}
    <thead class="text-xs sm:text-sm text-gray-700 uppercase bg-gray-50">
        <tr>
            <th scope="col" class="px-2 py-3 sm:px-6 sm:py-3">Issue Type</th>
            <th scope="col" class="px-2 py-3 sm:px-6 sm:py-3">Location</th>
            <th scope="col" class="px-2 py-3 sm:px-6 sm:py-3 hidden md:table-cell">Assigned To</th>
            <th scope="col" class="px-2 py-3 sm:px-6 sm:py-3">Status</th>
            <th scope="col" class="px-2 py-3 sm:px-6 sm:py-3 hidden md:table-cell">Created By</th>
            <th scope="col" class="px-2 py-3 sm:px-6 sm:py-3">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for p in page %}
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b">
                <th scope="row"
                    class="px-2 py-3 sm:px-6 sm:py-4 font-medium text-gray-900 ">{{ p.issue_type.name }}</th>
                <td class="px-2 py-3 sm:px-6 sm:py-4">{{ p.location.name }}</td>
                <td class="px-2 py-3 sm:px-6 sm:py-4 hidden md:table-cell">{{ p.department.name }}</td>
                <td class="px-2 py-3 sm:px-6 sm:py-4 lowercase first-letter:capitalize">{{ p.status }}</td>
                <td class="px-2 py-3 sm:px-6 sm:py-4 hidden md:table-cell">{{ p.created_by.username }}</td>
                <td class="px-2 py-3 sm:px-6 sm:py-4">
                    <a href="{{ p.get_absolute_url }}"
                       class="font-semibold text-gray-600 hover:underline">Detail</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
{% endblock table %}