job/urls.py
from django.urls import path, include
from . import views

app_name = "job"

urlpatterns = [
    path("jobs/get", views.get_jobs, name="get_jobs"),
    path("list", views.list, name="list"),
    path("detail/<int:id>", views.detail, name="detail"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("test/list", views.test_list, name="test_list"),
    path("test/detail/<int:id>", views.test_detail, name="test_detail"),
    path("test/finish/<int:id>", views.finish_test, name="finish_test"),
    path("test/next-machine/<int:id>", views.next_machine, name="next_machine"),
    # path("test/edit/<int:id>", views.test_edit, name="test_edit"),
    path("test/create/<int:id>", views.create_test, name="create_test"),
    path(
        "test/semi-waste/create/<int:id>",
        views.create_semi_waste,
        name="create_semi_waste",
    ),
]

main/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password/change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/profile/password/change.html"
        ),
        name="password_change",
    ),
    path(
        "password/change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/profile/password/done.html"
        ),
        name="password_change_done",
    ),
    path("", include("account.urls")),
    path("approval/", include("approval.urls")),
    path("product/", include("product.urls")),
    path("job/", include("job.urls")),
    path("misc/", include("misc.urls")),
    path("machine/", include("machine.urls")),
    path("assessment/", include("assessment.urls")),
    path("she/", include("she.urls")),
    path("report/", include("report.urls")),
    re_path(r"^session_security/", include("session_security.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she/urls.py
from django.urls import path
from . import views

app_name = "she"

urlpatterns = [
    # path("edit/<int:id>", views.edit, name="edit"),
    path("issue/list", views.issue_list, name="issue_list"),
    path("issue/create", views.create_issue, name="create_issue"),
    path("issue/detail/<int:id>", views.issue_detail, name="issue_detail"),
    path(
        "status/update/<int:id>/<str:action>", views.update_status, name="update_status"
    ),
    path("incident/list", views.incident_list, name="incident_list"),
    path("incident/create", views.create_incident, name="create_incident"),
    path("incident/detail/<int:id>", views.incident_detail, name="incident_detail"),
    path("department/list", views.department_list, name="department_list"),
    path("department/get", views.get_departments, name="get_departments"),
    path("employee/list", views.employee_list, name="employee_list"),
    path("employee/get", views.get_employees, name="get_employees"),
    path("location/list", views.location_list, name="location_list"),
    path("location/create", views.create_location, name="create_location"),
    path("location/edit/<int:id>", views.edit_location, name="edit_location"),
    path("issue/type/list", views.issue_type_list, name="issue_type_list"),
    path("issue/type/create", views.create_issue_type, name="create_issue_type"),
    path("issue/type/edit/<int:id>", views.edit_issue_type, name="edit_issue_type"),
    path("incident/type/list", views.incident_type_list, name="incident_type_list"),
    path(
        "incident/type/create", views.create_incident_type, name="create_incident_type"
    ),
    path(
        "incident/type/edit/<int:id>",
        views.edit_incident_type,
        name="edit_incident_type",
    ),
    path(
        "fire-prevention/list", views.fire_prevention_list, name="fire_prevention_list"
    ),
    path(
        "fire-prevention/create",
        views.create_fire_prevention,
        name="create_fire_prevention",
    ),
    path(
        "fire-prevention/detail/<int:id>",
        views.fire_prevention_detail,
        name="fire_prevention_detail",
    ),
    path(
        "fire-prevention/checklist/save/<int:id>",
        views.save_fp_checklist,
        name="save_fp_checklist",
    ),
    path(
        "fire-prevention/checkpoint/list", views.checkpoint_list, name="checkpoint_list"
    ),
    path(
        "fire-prevention/checkpoint/create",
        views.create_checkpoint,
        name="create_checkpoint",
    ),
    path(
        "fire-prevention/checkpoint/edit/<int:id>",
        views.edit_checkpoint,
        name="edit_checkpoint",
    ),
]

templates/incident/type/create.html
{% extends "form.html" %}
{% block title %}Create Incident Type{% endblock %}
{% block form %}
    <div class=" bg-gray-50">
        <form class="p-4 md:p-5 "
              method="post"
              action="{% url 'she:create_incident_type' %}">
            {% csrf_token %}
            <div class="flex-col gap-2 mb-4 mx-auto">
                <p class="text-red-700 text-sm">
                    {% if form.non_field_errors %}{{ form.non_field_errors|join:", " }}{% endif %}
                </p>
                <div class="grid  gap-2 mb-4">
                    {% for field in form %}
                        <div class="flex-col mb-3">
                            <div class=" mb-2 ">{{ field.label_tag }}</div>
                            <div class="flex ">{{ field }}</div>
                            <p class="text-red-700 text-sm">
                                {% if field.errors %}{{ field.errors|join:", " }}{% endif %}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="flex gap-4">
                <button type="submit"
                        class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Create
                </button>
                <a href="{% url 'she:incident_type_list' %}"
                   class=" inline-flex items-center bg-gray-200 hover:bg-gray-300 focus:ring-2 focus:outline-none focus:ring-gray-400 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Cancel
                </a>
            </div>
        </form>
        {{ form.media }}
    </div>
{% endblock form %}

templates/incident/type/detail.html
<!-- Modal toggle -->
<button data-modal-target="detail-{{ p.id }}"
        data-modal-toggle="detail-{{ p.id }}"
        class="block text-white bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center "
        type="button">Detail</button>
<!-- Main modal -->
<div id="detail-{{ p.id }}"
     tabindex="-1"
     aria-hidden="true"
     class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 ">Incident Type Detail</h3>
                <button type="button"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg  w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-toggle="detail-{{ p.id }}">
                    <svg class="w-3 h-3"
                         aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5">
                <ul class="max-w-md divide-y divide-gray-200 dark:divide-gray-700 mb-2">
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center  font-semibold text-gray-900 ">Name</div>
                            <div class="flex-row text-right">
                                <p class=" font-medium text-gray-900 truncate ">{{ p.name }}</p>
                            </div>
                        </div>
                    </li>
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center  font-semibold text-gray-900 ">Active</div>
                            <div class="flex-row text-right">
                                <p class=" font-medium text-gray-900 truncate ">{{ p.active }}</p>
                            </div>
                        </div>
                    </li>
                </ul>
                <div class="text-right">
                    <a href="{% url 'she:edit_incident_type' p.id %}"
                       class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                        Edit
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/incident/type/edit.html
{% extends "form.html" %}
{% block title %}
    Edit Incident Type
{% endblock title %}
{% block form %}
    <div class=" bg-gray-50">
        <form class="p-4 md:p-5 "
              method="post"
              action="{% url 'she:edit_incident_type' incident_type.id %}">
            {% csrf_token %}
            <div class="grid sm:grid-cols-2 gap-2 mb-4 mx-auto">
                {% for field in form %}
                    <div>
                        {{ field.label_tag }}
                        <div class="flex-col ">{{ field }}</div>
                    </div>
                {% endfor %}
            </div>
            <div class="flex gap-4">
                <button type="submit"
                        class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Save
                </button>
                <a href="{% url 'she:incident_type_list' %}"
                   class=" inline-flex items-center bg-gray-200 hover:bg-gray-300 focus:ring-2 focus:outline-none focus:ring-gray-400 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Cancel
                </a>
            </div>
        </form>
        {{ form.media }}
    </div>
{% endblock form %}

templates/incident/type/list.html
{% extends "partials/table.html" %}
{% block title %}Incident Type List{% endblock %}
{% block buttons %}
    <a href="{% url 'she:create_incident_type' %}"
       class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
        Create
    </a>
    {% include "partials/filter.html" %}
{% endblock buttons %}
{% block table %}
    <thead class="text-xs sm:text-sm text-gray-700 uppercase bg-gray-50">
        <tr>
            <th scope="col" class="px-3 sm:px-6 py-3">Name</th>
            <th scope="col" class="px-3 sm:px-6 py-3">Active</th>
            <th scope="col" class="px-3 sm:px-6 py-3 text-right">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for p in page %}
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b">
                <th scope="row" class="px-3 sm:px-6 py-3 font-medium text-gray-900 ">
                    <p>{{ p.name }}</p>
                </th>
                <td class="px-3 sm:px-6 py-3 capitalize">{{ p.active }}</td>
                <td class="px-3 sm:px-6 py-3 flex justify-end">{% include 'incident/type/detail.html' %}</td>
            </tr>
        {% endfor %}
    </tbody>
{% endblock table %}