job/urls.py
from django.urls import path, include
from . import views

app_name = "job"

urlpatterns = [
    path("jobs/get", views.get_jobs, name="get_jobs"),
    path("list", views.list, name="list"),
    path("detail/<int:id>", views.detail, name="detail"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("test/list", views.test_list, name="test_list"),
    path("test/detail/<int:id>", views.test_detail, name="test_detail"),
    path("test/finish/<int:id>", views.finish_test, name="finish_test"),
    path("test/next-machine/<int:id>", views.next_machine, name="next_machine"),
    # path("test/edit/<int:id>", views.test_edit, name="test_edit"),
    path("test/create/<int:id>", views.create_test, name="create_test"),
    path(
        "test/semi-waste/create/<int:id>",
        views.create_semi_waste,
        name="create_semi_waste",
    ),
]

main/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password/change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/profile/password/change.html"
        ),
        name="password_change",
    ),
    path(
        "password/change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/profile/password/done.html"
        ),
        name="password_change_done",
    ),
    path("", include("account.urls")),
    path("approval/", include("approval.urls")),
    path("product/", include("product.urls")),
    path("job/", include("job.urls")),
    path("misc/", include("misc.urls")),
    path("machine/", include("machine.urls")),
    path("assessment/", include("assessment.urls")),
    path("she/", include("she.urls")),
    path("report/", include("report.urls")),
    re_path(r"^session_security/", include("session_security.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misc/urls.py
from django.urls import path
from . import views

app_name = "misc"

urlpatterns = [
    path("customer/list", views.customer_list, name="customer_list"),
    path("customer/get", views.get_customers, name="get_customers"),
    path("raw_material/list", views.raw_material_list, name="raw_material_list"),
    path("raw_material/create", views.create_raw_material, name="create_raw_material"),
    path(
        "raw_material/<int:id>/edit", views.edit_raw_material, name="edit_raw_material"
    ),
    path("shift/list", views.shift_list, name="shift_list"),
    path("shift/create", views.create_shift, name="create_shift"),
    path("shift/<int:id>/edit", views.edit_shift, name="edit_shift"),
    path("color/list", views.color_list, name="color_list"),
    path("color/create", views.create_color, name="create_color"),
    path("color/<int:id>/edit", views.edit_color, name="edit_color"),
    path("color_standard/list", views.color_standard_list, name="color_standard_list"),
    path(
        "color_standard/create",
        views.create_color_standard,
        name="create_color_standard",
    ),
    path(
        "color_standard/<int:id>/edit",
        views.edit_color_standard,
        name="edit_color_standard",
    ),
]

misc/models.py
from django.db import models
from django.urls import reverse
from django.db.models.functions import Lower


class Customer(models.Model):
    no = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class ColorStandard(models.Model):
    name = models.CharField(max_length=100, unique=True)
    colors = models.ManyToManyField(
        "misc.Color",
        blank=True,
        related_name="color_standards",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                Lower("name"), name="unique_case_insensitive_color_standard_name"
            )
        ]
        ordering = ["name"]

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=100, unique=True)
    viscosity = models.FloatField(default=0)
    code = models.CharField(max_length=100, unique=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                Lower("name"), name="unique_case_insensitive_color_name"
            )
        ]
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}-{self.code}"


class RawMaterial(models.Model):
    name = models.CharField(max_length=100)
    thickness = models.IntegerField(null=True, blank=True)


    class Meta:
        # constraints = [
        #     models.UniqueConstraint(
        #         Lower("name"), name="unique_case_insensitive_RM_name"
        #     )
        # ]
        ordering = ["name",'thickness']

    def __str__(self):
        if self.thickness == None:
            return self.name
        else:
            return f"{self.name} - {self.thickness}"


class Shift(models.Model):
    code = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                Lower("name"), name="unique_case_insensitive_shift_name"
            )
        ]
        ordering = ["name"]

    def __str__(self):
        return self.name


# class Unit(models.Model):
#     name = models.CharField(max_length=100)
#     description = models.TextField()

#     def __str__(self):
#         return self.name

misc/forms.py
from django import forms
from django_select2 import forms as s2forms
from django.forms import formset_factory, inlineformset_factory
from .models import RawMaterial, Shift, Color, ColorStandard
from main.custom_widgets import ColorWidget


class CreateRawMaterialForm(forms.ModelForm):
    class Meta:
        model = RawMaterial
        fields = [ "name", 'thickness']


class EditRawMaterialForm(forms.ModelForm):
    class Meta:
        model = RawMaterial
        fields = [ "name", 'thickness']


class CreateShiftForm(forms.ModelForm):
    class Meta:
        model = Shift
        fields = ["code", "name"]


class EditShiftForm(forms.ModelForm):
    class Meta:
        model = Shift
        fields = ["code", "name"]


class CreateColorStandardForm(forms.ModelForm):
    class Meta:
        model = ColorStandard
        fields = ("name", "colors")
        widgets = {
            "name": forms.TextInput(attrs={"class": "w-full text-center h-auto"}),
        }

    colors = forms.ModelMultipleChoiceField(
        queryset=Color.objects.all(),
        widget=s2forms.ModelSelect2MultipleWidget(
            queryset=Color.objects.all(),
            search_fields=[
                "name__icontains",
                "code__icontains",
            ],
            attrs={"class": "w-full text-center h-auto"},
        ),
    )


class EditColorStandardForm(forms.ModelForm):
    class Meta:
        model = ColorStandard
        fields = ["colors"]

    colors = forms.ModelMultipleChoiceField(
        queryset=Color.objects.all(),
        widget=s2forms.ModelSelect2MultipleWidget(
            queryset=Color.objects.all(),
            search_fields=[
                "name__icontains",
                "code__icontains",
            ],
            attrs={"class": "w-full text-center h-auto"},
        ),
    )


class CreateColorForm(forms.ModelForm):
    class Meta:
        model = Color
        fields = ["name", "code", "viscosity"]


class EditColorForm(forms.ModelForm):
    class Meta:
        model = Color
        fields = ["name", "code", "viscosity"]

misc/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from job.models import  JobTest
from .models import Color, ColorStandard, Customer, RawMaterial, Shift
from main.tasks import get_page, role_check
from .tasks import (
    customer_get,
    raw_material_create,
    raw_material_edit,
    shift_create,
    shift_edit,
    color_create,
    color_edit,
    color_standard_edit,
)
from .filters import (
    CustomerFilter,
    ColorFilter,
    ColorStandardFilter,
    RawMaterialFilter,
    ShiftFilter,
)
from .forms import (
    CreateRawMaterialForm,
    EditRawMaterialForm,
    CreateShiftForm,
    EditShiftForm,
    CreateColorForm,
    EditColorForm,
    CreateColorStandardForm,
    EditColorStandardForm,
)


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def customer_list(request):
    customers = Customer.objects.all()
    customer_filter = CustomerFilter(request.GET, queryset=customers)
    customers = customer_filter.qs
    page = get_page(request, model=customers)

    context = {
        "page": page,
        "filter": customer_filter,
    }
    return render(request, "misc/customer/list.html", context)


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def get_customers(request):
    customer_get()
    return redirect("misc:customer_list")


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def raw_material_list(request):
    raw_materials = RawMaterial.objects.all()
    raw_material_filter = RawMaterialFilter(request.GET, queryset=raw_materials)
    raw_materials = raw_material_filter.qs
    page = get_page(request, model=raw_materials)
    context = {
        "page": page,
        "filter": raw_material_filter,
    }
    return render(request, "misc/raw_material/list.html", context)


@login_required
@role_check(["ADMIN", "MANAGER", "SUPERVISOR"])
def create_raw_material(request):
    if request.method == "GET":
        form = CreateRawMaterialForm()
        context = {"form": form}
        return render(request, "misc/raw_material/create.html", context)

    raw_material_create(request)
    return redirect("misc:raw_material_list")


@login_required
@role_check(["ADMIN", "MANAGER", "SUPERVISOR"])
def edit_raw_material(request, id):
    if request.method == "GET":
        raw_material = get_object_or_404(RawMaterial, id=id)
        form = EditRawMaterialForm(instance=raw_material)
        context = {"form": form, "raw_material": raw_material}
        return render(request, "misc/raw_material/edit.html", context)

    raw_material_edit(request, id)
    return redirect("misc:raw_material_list")


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def shift_list(request):
    shifts = Shift.objects.all()
    shift_filter = ShiftFilter(request.GET, queryset=shifts)
    shifts = shift_filter.qs
    page = get_page(request, model=shifts)
    context = {
        "page": page,
        "filter": shift_filter,
    }
    return render(request, "misc/shift/list.html", context)


@login_required
@role_check(["ADMIN", "MANAGER", "SUPERVISOR"])
def create_shift(request):
    if request.method == "GET":
        form = CreateShiftForm()
        context = {"form": form}
        return render(request, "misc/shift/create.html", context)

    shift_create(request)
    return redirect("misc:shift_list")


@login_required
@role_check(["ADMIN", "MANAGER", "SUPERVISOR"])
def edit_shift(request, id):
    if request.method == "GET":
        shift = get_object_or_404(Shift, id=id)
        form = EditShiftForm(instance=shift)
        context = {"form": form, "shift": shift}
        return render(request, "misc/shift/edit.html", context)

    shift_edit(request, id)
    return redirect("misc:shift_list")


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def color_list(request):
    colors = Color.objects.all()
    color_filter = ColorFilter(request.GET, queryset=colors)
    colors = color_filter.qs
    page = get_page(request, model=colors)
    context = {
        "page": page,
        "filter": color_filter,
    }
    return render(request, "misc/color/list.html", context)


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def create_color(request):
    if request.method == "GET":
        form = CreateColorForm()
        context = {"form": form}
        return render(request, "misc/color/create.html", context)

    color_create(request)
    return redirect("misc:color_list")


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def edit_color(request, id):
    if request.method == "GET":
        color = get_object_or_404(Color, id=id)
        form = EditColorForm(instance=color)
        context = {"form": form, "color": color}
        return render(request, "misc/color/edit.html", context)

    color_edit(request, id)
    return redirect("misc:color_list")


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def color_standard_list(request):
    color_standards = ColorStandard.objects.prefetch_related("colors").all()
    color_standard_filter = ColorStandardFilter(request.GET, queryset=color_standards)
    color_standards = color_standard_filter.qs
    page = get_page(request, model=color_standards)
    context = {
        "page": page,
        "filter": color_standard_filter,
    }
    return render(request, "misc/color_standard/list.html", context)


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def create_color_standard(request):
    if request.method == "POST":

        form = CreateColorStandardForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            color_standard = ColorStandard(name=name)
            color_standard.save()
            color_standard.colors.set(form.cleaned_data.get("colors"))
            color_standard.save()
            return redirect("misc:color_standard_list")
    else:
        form = CreateColorStandardForm()
    context = {
        "form": form,
    }
    return render(request, "misc/color_standard/create.html", context)


@login_required
@role_check(["ADMIN", "MANAGER", "INSPECTOR", "SUPERVISOR"])
def edit_color_standard(request, id):
    color_standard = get_object_or_404(ColorStandard, id=id)
    open_job_tests = JobTest.objects.filter(color_standard=color_standard)
    if open_job_tests.exists:
        return redirect("misc:color_standard_list")
    if request.method == "POST":
        form = EditColorStandardForm(request.POST)
        if form.is_valid():
            colors = form.cleaned_data.get("colors")
            color_standard.colors.set(colors)
            color_standard.save()
            return redirect("misc:color_standard_list")
    else:
        form = EditColorStandardForm(instance=color_standard)
    context = {"form": form, "color_standard": color_standard}
    return render(request, "misc/color_standard/edit.html", context)

templates/misc/color/create.html
{% extends "form.html" %}
{% block title %}Create Color{% endblock %}
{% block form %}
    <div class=" bg-gray-50">
        <form class="p-4 md:p-5 "
              method="post"
              action="{% url 'misc:create_color' %}">
            {% csrf_token %}
            <div class="flex-col gap-2 mb-4 mx-auto">
                <p class="text-red-700 text-sm">
                    {% if form.non_field_errors %}{{ form.non_field_errors|join:", " }}{% endif %}
                </p>
                <div class="grid sm:grid-cols-2 gap-2 mb-4">
                    {% for field in form %}
                        <div class="flex-col mb-3">
                            <div class=" mb-2 ">{{ field.label_tag }}</div>
                            <div class="flex ">{{ field }}</div>
                            <p class="text-red-700 text-sm">
                                {% if field.errors %}{{ field.errors|join:", " }}{% endif %}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="flex gap-4">
                <button type="submit"
                        class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Create
                </button>
                <a href="{% url 'misc:color_list' %}"
                   class=" inline-flex items-center bg-gray-200 hover:bg-gray-300 focus:ring-2 focus:outline-none focus:ring-gray-400 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Cancel
                </a>
            </div>
        </form>
        {{ form.media }}
    </div>
{% endblock form %}

templates/misc/color/detail.html
<!-- Modal toggle -->
<button data-modal-target="color-detail-{{ c.id }}"
        data-modal-toggle="color-detail-{{ c.id }}"
        class="block text-white bg-gray-800 hover:bg-gray-900 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center "
        type="button">Detail</button>
<!-- Main modal -->
<div id="color-detail-{{ c.id }}"
     tabindex="-1"
     aria-hidden="true"
     class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 ">Color Detail</h3>
                <button type="button"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-base w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-toggle="color-detail-{{ c.id }}">
                    <svg class="w-3 h-3"
                         aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5">
                <ul class="max-w-md divide-y divide-gray-200 dark:divide-gray-700">
                    <li class="pb-3 sm:pb-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center text-base font-semibold text-gray-900 ">Code</div>
                            <div class="flex-row text-right">
                                <p class="text-base font-medium text-gray-900 truncate ">{{ c.code }}</p>
                            </div>
                        </div>
                    </li>
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center text-base font-semibold text-gray-900 ">Name</div>
                            <div class="flex-row text-right">
                                <p class="text-base font-medium text-gray-900 truncate ">{{ c.name }}</p>
                            </div>
                        </div>
                    </li>
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center text-base font-semibold text-gray-900 ">Viscosity</div>
                            <div class="flex-row text-right">
                                <p class="text-base font-medium text-gray-900 truncate ">{{ c.viscosity }}</p>
                            </div>
                        </div>
                    </li>
                    <li class="pb-3 sm:pb-4">
                        <div class="text-left font-semibold text-lg text-gray-700 mb-2">Color Standards</div>
                        <div class="grid justify-items-stretch grid-cols-2">
                            {% for color in c.color_standards.all %}
                                <div class="flex-row align-top">
                                    <p class="text-base font-medium text-gray-900 ">> {{ color.name }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </li>
                </ul>
                <div class="text-right">
                    <a href="{% url 'misc:edit_color' c.id %}"
                       class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                        Edit
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/misc/color/edit.html
{% extends "form.html" %}
{% block title %}Edit Color{% endblock %}
{% block form %}
    <div class=" bg-gray-50">
        <form class="p-4 md:p-5 "
              method="post"
              action="{% url 'misc:edit_color' color.id %}">
            {% csrf_token %}
            <div class="flex gap-2 mb-4 mx-auto">
                <div class="flex-col  font-semibold tracking-wider">Color:</div>
                <div class="flex-col font-normal">
                    <p class="  text-base  text-gray-700 tracking-wider uppercase">{{ color.name }}</p>
                </div>
            </div>
            <div class="flex-col gap-2 mb-4 mx-auto">
                <p class="text-red-700 text-sm">
                    {% if form.non_field_errors %}{{ form.non_field_errors|join:", " }}{% endif %}
                </p>
                <div class="grid sm:grid-cols-2 gap-2 mb-4">
                    {% for field in form %}
                        <div class="flex-col mb-3">
                            <div class=" mb-2 ">{{ field.label_tag }}</div>
                            <div class="flex ">{{ field }}</div>
                            <p class="text-red-700 text-sm">
                                {% if field.errors %}{{ field.errors|join:", " }}{% endif %}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="flex gap-4">
                <button type="submit"
                        class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Save
                </button>
                <a href="{% url 'misc:color_list' %}"
                   class=" inline-flex items-center bg-gray-200 hover:bg-gray-300 focus:ring-2 focus:outline-none focus:ring-gray-400 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Cancel
                </a>
            </div>
        </form>
        {{ form.media }}
    </div>
{% endblock form %}

templates/misc/color/list.html
{% extends "partials/table.html" %}
{% block title %}Color List{% endblock %}
{% block buttons %}
    <a href="{% url 'misc:create_color' %}"
       class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
        Create
    </a>
    {% include "partials/filter.html" %}
{% endblock buttons %}
{% block table %}
    <thead class="text-xs sm:text-sm text-gray-700 uppercase bg-gray-50">
        <tr>
            <th scope="col" class=" px-2 py-2 sm:px-6 sm:py-3">Code</th>
            <th scope="col" class=" px-2 py-2 sm:px-6 sm:py-3">Name</th>
            <th scope="col" class=" px-2 py-2 sm:px-6 sm:py-3 text-right">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for c in page %}
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b">
                <td class="px-2 py-2 sm:px-6 sm:py-3 capitalize">{{ c.code }}</td>
                <th scope="row"
                    class="px-2 py-2 sm:px-6 sm:py-3 font-medium text-gray-900 ">
                    <p>{{ c.name }}</p>
                </th>
                <td class="px-2 py-2 sm:px-6 sm:py-3 flex justify-end">{% include 'misc/color/detail.html' %}</td>
            </tr>
        {% endfor %}
    </tbody>
{% endblock table %}