job/urls.py
from django.urls import path, include
from . import views

app_name = "job"

urlpatterns = [
    path("jobs/get", views.get_jobs, name="get_jobs"),
    path("list", views.list, name="list"),
    path("detail/<int:id>", views.detail, name="detail"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("test/list", views.test_list, name="test_list"),
    path("test/detail/<int:id>", views.test_detail, name="test_detail"),
    path("test/finish/<int:id>", views.finish_test, name="finish_test"),
    path("test/next-machine/<int:id>", views.next_machine, name="next_machine"),
    # path("test/edit/<int:id>", views.test_edit, name="test_edit"),
    path("test/create/<int:id>", views.create_test, name="create_test"),
    path(
        "test/semi-waste/create/<int:id>",
        views.create_semi_waste,
        name="create_semi_waste",
    ),
]

main/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password/change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/profile/password/change.html"
        ),
        name="password_change",
    ),
    path(
        "password/change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/profile/password/done.html"
        ),
        name="password_change_done",
    ),
    path("", include("account.urls")),
    path("approval/", include("approval.urls")),
    path("product/", include("product.urls")),
    path("job/", include("job.urls")),
    path("misc/", include("misc.urls")),
    path("machine/", include("machine.urls")),
    path("assessment/", include("assessment.urls")),
    path("she/", include("she.urls")),
    path("report/", include("report.urls")),
    re_path(r"^session_security/", include("session_security.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.urls import path
from . import views

app_name = "report"

urlpatterns = [
    path(
        "assessment/get/<int:id>",
        views.get_assessment_report,
        name="get_assessment_report",
    ),
    path(
        "assessments/get/<int:id>",
        views.get_assessments_report,
        name="get_assessments_report",
    ),
    path(
        "fire-prevention/get/<int:id>",
        views.get_fire_prevention_report,
        name="get_fire_prevention_report",
    ),
    path(
        "incident/get/<int:id>",
        views.get_incident_report,
        name="get_incident_report",
    ),
    path("header/list", views.header_list, name="header_list"),
    path("header/create", views.create_header, name="create_header"),
    path("header/edit/<int:id>", views.edit_header, name="edit_header"),
]

report/models.py
import datetime
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User as auth_user

REPORT_LIST = (
    ("FIRST-OFF", "FIRST-OFF"),
    ("ON-PROCESS", "ON-PROCESS"),
    ("FIRE-PREVENTION", "FIRE-PREVENTION"),
    ("INCIDENT", "INCIDENT"),
)


class ReportHeader(models.Model):
    report = models.CharField(max_length=20, choices=REPORT_LIST)
    no = models.CharField(max_length=30)
    issue_no = models.IntegerField(default=1)
    effective_date = models.DateField(default=timezone.now)
    machine = models.ForeignKey(
        "machine.Machine",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="report_header",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    by = models.ForeignKey(auth_user, on_delete=models.RESTRICT, null=True, blank=True)

    def __str__(self):
        if self.machine:
            return f"{self.no} - {self.machine.name}"
        else:
            return f"{self.no}"

    class Meta:
        ordering = ["no"]
        unique_together = ("report", "machine", "issue_no")

report/forms.py
from django import forms
from django_select2 import forms as s2forms
from .models import ReportHeader
from machine.models import Machine


class CreateReportHeaderForm(forms.ModelForm):
    class Meta:
        model = ReportHeader
        fields = ("report", "effective_date", "issue_no", "machine", "no")
        widgets = {
            "report": forms.Select(attrs={"class": "w-full text-center h-auto"}),
            "no": forms.TextInput(attrs={"class": "w-full text-center h-auto"}),
            "issue_no": forms.NumberInput(attrs={"class": "w-full text-center h-auto"}),
            "effective_date": forms.DateInput(
                attrs={"class": "w-full text-center h-auto", "type": "date"}
            ),
        }
        labels = {
            "report": "Report Type",
            "effective_date": "Effective Date",
            "issue_no": "Issue No",
            "no": "Document No",
            "machine": "Machine",
        }

    machine = forms.ModelChoiceField(
        required=False,
        queryset=Machine.objects.all(),
        widget=s2forms.ModelSelect2Widget(
            model=Machine,
            max_results=4,
            search_fields=["name__icontains"],
            attrs={"class": "w-full text-center h-auto"},
        ),
    )

    def clean(self):
        cleaned_data = super().clean()
        report = cleaned_data.get("report")
        issue_no = cleaned_data.get("issue_no")
        effective_date = cleaned_data.get("effective_date")
        last_effective_dates = ReportHeader.objects.filter(report=report).order_by(
            "-issue_no"
        )
        machine = cleaned_data.get("machine")
        if report in ["FIRST-OFF", "ON-PROCESS"]:
            if machine is None:
                self.add_error(
                    "machine",
                    f"Machine can't be empty for {report} report",
                )
        else:
            if ReportHeader.objects.filter(report=report, issue_no=issue_no).exists():
                self.add_error(
                    "report", f"{report} with issue no {issue_no} already exists"
                )
        if ReportHeader.objects.filter(
            report=report, effective_date=effective_date
        ).exists():
            self.add_error(
                "effective_date",
                f"{report} with effective date {effective_date} already exists",
            )
        if issue_no < 1:
            self.add_error("issue_no", "Issue no can't be less than 1")
        if last_effective_dates.exists():
            if effective_date < last_effective_dates.first().effective_date:
                self.add_error(
                    "effective_date",
                    f"Effective date can't be less than {last_effective_dates.first().effective_date}",
                )
        return cleaned_data


class EditReportHeaderForm(forms.ModelForm):
    class Meta:
        model = ReportHeader
        fields = ("issue_no", "effective_date", "no")
        widgets = {
            "no": forms.TextInput(attrs={"class": "w-full text-center h-auto"}),
        }

    def clean(self):
        cleaned_data = super().clean()
        report = cleaned_data.get("report")
        issue_no = cleaned_data.get("issue_no")
        effective_date = cleaned_data.get("effective_date")
        last_effective_dates = ReportHeader.objects.filter(report=report).order_by(
            "-issue_no"
        )
        machine = cleaned_data.get("machine")
        if report in ["FIRST-OFF", "ON-PROCESS"]:
            if machine is None:
                self.add_error(
                    "machine",
                    f"Machine can't be empty for {report} report",
                )
        else:
            if ReportHeader.objects.filter(report=report, issue_no=issue_no).exists():
                self.add_error(
                    "report", f"{report} with issue no {issue_no} already exists"
                )
        if ReportHeader.objects.filter(
            report=report, effective_date=effective_date
        ).exists():
            self.add_error(
                "effective_date",
                f"{report} with effective date {effective_date} already exists",
            )
        if issue_no < 1:
            self.add_error("issue_no", "Issue no can't be less than 1")
        if last_effective_dates.exists():
            if effective_date < last_effective_dates.first().effective_date:
                self.add_error(
                    "effective_date",
                    f"Effective date can't be less than {last_effective_dates.first().effective_date}",
                )
        return cleaned_data

report/views.py
from io import BytesIO
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from main.tasks import get_page, role_check
from django.http import FileResponse
from job.models import JobTest
from assessment.models import Assessment
from .models import ReportHeader
from she.models import FirePrevention, Incident
from report.reports.assessment import FirstOffReport, OnProcessReport
from report.reports.fire_prevention import FirePreventionReport
from report.reports.incident import IncidentReport
from .forms import CreateReportHeaderForm, EditReportHeaderForm


@login_required
@role_check(["ADMIN", "MANAGER", "SAFETY"])
def header_list(request):
    headers = ReportHeader.objects.all()

    page = get_page(request, model=headers)

    context = {
        "page": page,
    }
    return render(request, "report/header/list.html", context)

@login_required
@role_check(["ADMIN", "MANAGER", "SAFETY"])
def create_header(request):
    if request.method == "POST":
        form = CreateReportHeaderForm(request.POST)
        if form.is_valid():
            header = form.save(commit=False)
            header.by = request.user
            header.save()
            return redirect("report:header_list")
    else:
        form = CreateReportHeaderForm()
    context = {
        "form": form,
    }
    return render(request, "report/header/create.html", context)

@login_required
@role_check(["ADMIN", "MANAGER", "SAFETY"])
def edit_header(request, id):
    header = get_object_or_404(ReportHeader, id=id)
    if request.method == "POST":
        form = EditReportHeaderForm(request.POST, instance=header)
        if form.is_valid():
            header = form.save(commit=False)
            header.by = request.user
            header.save()
            return redirect("report:header_list")
    else:
        form = EditReportHeaderForm(instance=header)
    context = {
        "form": form,
        "header": header,
    }
    return render(request, "report/header/edit.html", context)


@login_required
def get_assessment_report(request, id):
    buffer = BytesIO()
    elements = []
    assessment = get_object_or_404(Assessment, id=id)
    if assessment.type == "FIRST-OFF":
        if assessment.report_header == None:
            return redirect("assessment:first_off_detail", id=id)
        first_off = FirstOffReport(
            buffer=buffer,
            elements=elements,
            assessment=assessment,
            id=assessment.job_test.id,
        )
        first_off.create()
        first_off.save()
    elif assessment.type == "ON-PROCESS":
        if assessment.report_header == None:
            return redirect("assessment:on_process_detail", id=id)
        on_process = OnProcessReport(
            buffer=buffer,
            elements=elements,
            assessment=assessment,
            id=assessment.job_test.id,
        )
        on_process.create()
        on_process.save()
    buffer.seek(0)
    response = FileResponse(
        buffer,
        content_type="application/pdf",
        as_attachment=True,
        filename=f"{assessment.job_test.job.no}-{assessment.job_test.job.product.name}-{assessment.job_test.no}-{assessment.type}.pdf",
    )
    return response


@login_required
def get_assessments_report(request, id):

    buffer = BytesIO()
    elements = []
    job_test = get_object_or_404(JobTest, id=id)
    assessments = Assessment.objects.filter(job_test=job_test).order_by(
        "route_no", "type", "date", "time"
    )
    for assessment in assessments:
        if assessment.report_header == None:
            return redirect("job:test_detail", id=id)
        if assessment.type == "FIRST-OFF":
            first_off = FirstOffReport(
                buffer=buffer,
                elements=elements,
                assessment=assessment,
                id=id,
            )
            first_off.create()
        elif assessment.type == "ON-PROCESS":
            on_process = OnProcessReport(
                buffer=buffer,
                elements=elements,
                assessment=assessment,
                id=id,
            )
            on_process.create()
    first_off.save()
    buffer.seek(0)
    response = FileResponse(
        buffer,
        content_type="application/pdf",
        as_attachment=True,
        filename=f"{job_test.job.no}-{job_test.no}-{job_test.job.product.name}.pdf",
    )

    return response


@login_required
def get_fire_prevention_report(request, id):
    buffer = BytesIO()
    elements = []
    fire_prevention = get_object_or_404(FirePrevention, id=id)
    report_header = ReportHeader.objects.filter(report="FIRE-PREVENTION").order_by(
        "-issue_no"
    )
    if report_header.exists():
        fire_prevention_report = FirePreventionReport(
            buffer=buffer,
            elements=elements,
            report_header=report_header,
            id=id,
        )
        fire_prevention_report.create()
        fire_prevention_report.save()
    else:
        return redirect("she:fire_prevention_detail", id=id)
    buffer.seek(0)
    response = FileResponse(
        buffer,
        content_type="application/pdf",
        as_attachment=True,
        filename=f"fire-prevention-{fire_prevention.shift.name}-{fire_prevention.created_at.date().strftime("%d-%m-%Y")}.pdf",
    )
    return response


@login_required
def get_incident_report(reqeust, id):
    buffer = BytesIO()
    elements = []
    incident = get_object_or_404(Incident, id=id)
    report_header = ReportHeader.objects.filter(report="INCIDENT").order_by("-issue_no")
    if report_header.exists():
        incident_report = IncidentReport(
            buffer=buffer,
            elements=elements,
            report_header=report_header,
            id=id,
        )
        incident_report.create()
        incident_report.save()
    else:
        return redirect("she:incident_detail", id=id)
    buffer.seek(0)
    response = FileResponse(
        buffer,
        content_type="application/pdf",
        as_attachment=True,
        filename=f"incident-{incident.employee.name}-{incident.date.strftime("%d-%m-%Y")}.pdf",
    )
    return response

templates/report/header/create.html
{% extends "form.html" %}
{% block title %}
    Create Report Header
{% endblock title %}
{% block form %}
    <div class=" bg-gray-50">
        <form class="p-4 md:p-5 "
              method="post"
              action="{% url 'report:create_header' %}">
            {% csrf_token %}
            <div class="flex-col gap-2 mb-4 mx-auto">
                <p class="text-red-700 text-sm">
                    {% if form.non_field_errors %}{{ form.non_field_errors|join:", " }}{% endif %}
                </p>
                <div class="grid sm:grid-cols-2 gap-2 mb-4 mx-auto">
                    {% for field in form %}
                        <div class="{% if field.name == 'no' %} col-span-2 {% endif %}">
                            <div class=" mb-2 ">{{ field.label_tag }}</div>
                            <div class="flex ">{{ field }}</div>
                            <p class="text-red-700 text-sm">
                                {% if field.errors %}{{ field.errors|join:", " }}{% endif %}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="flex gap-4">
                <button type="submit"
                        class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Create
                </button>
                <a href="{% url 'report:header_list' %}"
                   class=" inline-flex items-center bg-gray-200 hover:bg-gray-300 focus:ring-2 focus:outline-none focus:ring-gray-400 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Cancel
                </a>
            </div>
        </form>
        {{ form.media }}
    </div>
{% endblock form %}

templates/report/header/detail.html
<!-- Modal toggle -->
<button data-modal-target="detail-{{ p.id }}"
        data-modal-toggle="detail-{{ p.id }}"
        class="block text-white bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center "
        type="button">Detail</button>
<!-- Main modal -->
<div id="detail-{{ p.id }}"
     tabindex="-1"
     aria-hidden="true"
     class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 ">Report Header Detail</h3>
                <button type="button"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg  w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-toggle="detail-{{ p.id }}">
                    <svg class="w-3 h-3"
                         aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5">
                <ul class="max-w-md divide-y divide-gray-200 dark:divide-gray-700 mb-2">
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center  font-semibold text-gray-900 ">Report</div>
                            <div class="flex-row text-right">
                                <p class=" font-medium text-gray-900 truncate ">{{ p.report }}</p>
                            </div>
                        </div>
                    </li>
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center  font-semibold text-gray-900 ">Machine</div>
                            <div class="flex-row text-right">
                                <p class=" font-medium text-gray-900 truncate ">{{ p.machine.name }}</p>
                            </div>
                        </div>
                    </li>
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center  font-semibold text-gray-900 ">Document No.</div>
                            <div class="flex-row text-right">
                                <p class=" font-medium text-gray-900 truncate ">{{ p.no }}</p>
                            </div>
                        </div>
                    </li>
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center  font-semibold text-gray-900 ">Effective Date</div>
                            <div class="flex-row text-right">
                                <p class=" font-medium text-gray-900 truncate ">{{ p.effective_date }}</p>
                            </div>
                        </div>
                    </li>
                    <li class="py-3 sm:py-4">
                        <div class="flex items-center justify-between">
                            <div class="inline-flex  items-center  font-semibold text-gray-900 ">Issue No.</div>
                            <div class="flex-row text-right">
                                <p class=" font-medium text-gray-900 truncate ">{{ p.issue_no }}</p>
                            </div>
                        </div>
                    </li>
                </ul>
                <div class="text-right">
                    <a href="{% url 'report:edit_header' p.id %}"
                       class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                        Edit
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/report/header/edit.html
{% extends "form.html" %}
{% block title %}
    Edit Incident Type
{% endblock title %}
{% block form %}
    <div class=" bg-gray-50">
        <form class="p-4 md:p-5 "
              method="post"
              action="{% url 'report:edit_header' header.id %}">
            {% csrf_token %}
            <div class="grid sm:grid-cols-2 gap-2 mb-4 mx-auto">
                {% for field in form %}
                    <div class="{% if field.name == 'no' %} col-span-2 {% endif %}">
                        {{ field.label_tag }}
                        <div class="flex-col ">{{ field }}</div>
                    </div>
                {% endfor %}
            </div>
            <div class="flex gap-4">
                <button type="submit"
                        class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Save
                </button>
                <a href="{% url 'report:header_list' %}"
                   class=" inline-flex items-center bg-gray-200 hover:bg-gray-300 focus:ring-2 focus:outline-none focus:ring-gray-400 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
                    Cancel
                </a>
            </div>
        </form>
        {{ form.media }}
    </div>
{% endblock form %}

templates/report/header/list.html
{% extends "partials/table.html" %}
{% block title %}
    Report Header List
{% endblock title %}
{% block buttons %}
    <a href="{% url 'report:create_header' %}"
       class="text-white inline-flex items-center bg-gray-700 hover:bg-gray-800 focus:ring-2 focus:outline-none focus:ring-gray-300 font-medium rounded-lg uppercase text-xs tracking-widest  px-4 py-1.5 text-center">
        Create
    </a>
    {% include "partials/filter.html" %}
{% endblock buttons %}
{% block table %}
    <thead class="text-xs sm:text-sm text-gray-700 uppercase bg-gray-50">
        <tr>
            <th scope="col" class="px-3 sm:px-6 py-3">Name</th>
            <th scope="col" class="px-3 sm:px-6 py-3 ">Machine</th>
            <th scope="col" class="px-3 sm:px-6 py-3 hidden md:table-cell">Document No.</th>
            <th scope="col" class="px-3 sm:px-6 py-3 hidden md:table-cell">Issue No.</th>
            <th scope="col" class="px-3 sm:px-6 py-3 hidden md:table-cell">Effective Date</th>
            <th scope="col" class="px-3 sm:px-6 py-3 text-right">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for p in page %}
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b">
                <th scope="row" class="px-3 sm:px-6 py-3 font-medium text-gray-900 ">
                    <p>{{ p.report }}</p>
                </th>
                <td class="px-3 sm:px-6 py-3 capitalize ">{{ p.machine.name }}</td>
                <td class="px-3 sm:px-6 py-3 capitalize hidden md:table-cell">{{ p.no }}</td>
                <td class="px-3 sm:px-6 py-3 capitalize hidden md:table-cell">{{ p.issue_no }}</td>
                <td class="px-3 sm:px-6 py-3 capitalize hidden md:table-cell">{{ p.effective_date }}</td>
                <td class="px-3 sm:px-6 py-3 flex justify-end">{% include 'report/header/detail.html' %}</td>
            </tr>
        {% endfor %}
    </tbody>
{% endblock table %}